config/routes.rb
Rails.application.routes.draw do
  resources :testings

  # Defines the root path route ("/")
  root "events#index"

  get 'users/show'

  get 'static_pages/index'
  get 'static_pages/secret'

  devise_for :users

  resources :events, only: [:index, :show, :new, :create]
  
  get 'users/:id' => 'users#show', as: :user
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  scope '/checkout' do
    post 'create' => 'checkout#create', as: 'checkout_create' 
    get 'success' => 'checkout#success', as: 'checkout_success'
    get 'cancel' => 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :notify_admin_send


  def notify_admin_send
    admin = self.event.admin
    user = self.user
    AdminEventMailer.notify_admin(admin, user).deliver_now
  end

    belongs_to :user
    belongs_to :event
        
end

app/models/event.rb
class Event < ApplicationRecord
    validates :start_date,
    presence: true,
    comparison: { greater_than: Time.now}

    validates :duration,
    presence: true,
    numericality: { divisible_by: 5 }
    
    validates :title,
    presence: true,
    length: { in: 5..140 }

    validates :description,
    presence: true,
    length: { in: 20..1000 }

    validates :price,
    presence: true,
    numericality: { in: 1..1000 }

    validates :location,
    presence: true

    has_many :attendances
    belongs_to :admin, class_name: "User"
    has_many :users, through: :attendances

end

app/models/testing.rb
class Testing < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    after_create :welcome_send

    has_many :attendances
    has_many :attendances, foreign_key: 'admin_id', class_name: "Attendance"
    has_many :events, through: :attendances

    def welcome_send
        UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
    def create
      @total = params[:total].to_d
      @session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        line_items: [
          {
            price_data: {
              currency: 'eur',
              unit_amount: (@total*100).to_i,
              product_data: {
                name: 'Rails Stripe Checkout',
              },
            },
            quantity: 1
          },
        ],
        mode: 'payment',
        success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
        cancel_url: checkout_cancel_url
      )
      redirect_to @session.url, allow_other_host: true
    end
  
    def success
      @session = Stripe::Checkout::Session.retrieve(params[:session_id])
      @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
    end
  
    def cancel
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    @all_events = Event.all
    @user = current_user
  end

  def new
    @event = Event.new('start_date' => params[:start_date], 'duration' => params[:duration], 'title' => params[:title], 'description' => params[:description], 'price' => params[:price], 'location' => params[:location])
  end

  def create
    @event = Event.new(event_params)
    @event.admin_id = current_user.id
    if @event.save!
      redirect_to root_path
    else
      render :new
    end
    puts "*********"
    puts params[:start_date]
    puts "*********"
    puts params[:duration]
    puts "*********"
    puts params[:description]
    puts "*********"
    puts params[:location]
    puts "*********"
  end

  def show
    @event = Event.find(params[:id])
  end

  private 

  def event_params
    params.require(:event).permit(:title, :description, :start_date, :duration, :price, :location)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  
  def index
  end

  def secret
  end
end

app/controllers/testings_controller.rb
class TestingsController < ApplicationController
  before_action :set_testing, only: %i[ show edit update destroy ]

  # GET /testings or /testings.json
  def index
    @testings = Testing.all
  end

  # GET /testings/1 or /testings/1.json
  def show
  end

  # GET /testings/new
  def new
    @testing = Testing.new
  end

  # GET /testings/1/edit
  def edit
  end

  # POST /testings or /testings.json
  def create
    @testing = Testing.new(testing_params)

    respond_to do |format|
      if @testing.save
        format.html { redirect_to testing_url(@testing), notice: "Testing was successfully created." }
        format.json { render :show, status: :created, location: @testing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @testing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testings/1 or /testings/1.json
  def update
    respond_to do |format|
      if @testing.update(testing_params)
        format.html { redirect_to testing_url(@testing), notice: "Testing was successfully updated." }
        format.json { render :show, status: :ok, location: @testing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @testing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testings/1 or /testings/1.json
  def destroy
    @testing.destroy

    respond_to do |format|
      format.html { redirect_to testings_url, notice: "Testing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testing
      @testing = Testing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def testing_params
      params.require(:testing).permit(:username, :bio)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  before_action :authenticate_user!

  def show
    if is_current_user?
      @user = User.find(params[:id])
      @user_events = Event.where(admin_id: @user.id)
    else
      redirect_to events_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/testings_helper.rb
module TestingsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper

    def is_current_user?
        @user = User.find(params[:id])
        if current_user.id = @user.id
            return true
        end
    end
    
end

app/views/checkout/cancel.html.erb
<div class="container text-center my-5"> 
    <h1>Echec</h1> 
    <p>Le paiement n'a pas abouti.</p> 
</div> 

app/views/checkout/success.html.erb
<div class="container text-center my-5"> 
    <h1>Succès</h1> 
    <p>Nous avons bien reçu votre paiement de <%= number_to_currency(@payment_intent.amount_received / 100.0, unit: "€", separator: ",", delimiter: "", format: "%n %u") %>.</p>
    <p>Le statut de votre paiement est : <%= @payment_intent.status %>.</p> 
</div>

app/views/events/index.html.erb
<body>
     <div class="jumbotron">
        <div class="container text-center">
          <h1 class="display-3 ce">Bienvenue sur mon incroyable site !</h1>
          <p>Retrouvez ici tous vos événements prefs ! </p>
          <p>Puissiez-vous trouver votre bonheur ; des événements pêche party, de la TEUF TEUF, des conférences diverses et variées, des tranches de rigolade </p>
          <p>Viendez et bookez votre event ! </p>
          <p><a class="btn btn-primary btn-lg" href="/events/new" role="button">Clique ici pour créer ton event</a></p>
        </div>
      </div>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            <% @all_events.each do |event| %>
              <div class="col-md-4">
                <h2><%= event.title %></h2>
                <p><%= event.description %> </p>
                <p><a class="btn btn-secondary" href="/events/<%= event.id %>" role="button">Détails de l'event &raquo;</a></p>
              </div>
            <% end%>
        </div>
        <hr>
      </div> <!-- /container -->

    </main>

    <footer class="container">
      <p>&copy; Copyright 2023</p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
</body>

app/views/events/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Create New Event</title>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
  </head>
  <body>
    <div class="container">
      <h1>Créer un nouvel event</h1>
      <%= form_for @event, url: events_path, method: :post do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control', required: true %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control', required: true %>
        </div>
        <div class="form-group">
          <%= f.label :start_date %>
          <%= f.datetime_local_field :start_date, class: 'form-control', required: true %>
        </div>
        <div class="form-group">
          <%= f.label :duration %>
          <%= f.number_field :duration, class: 'form-control', min: 5, step: 5, required: true %>
        </div>
        <div class="form-group">
          <%= f.label :price %>
          <%= f.number_field :price, class: 'form-control', min: 1, max: 1000, required: true %>
        </div>
        <div class="form-group">
          <%= f.label :location %>
          <%= f.text_field :location, class: 'form-control', required: true %>
        </div>
        <%= f.submit "Create Event", class: 'btn btn-primary' %>
      <% end %>
    </div>
    <!-- Include jQuery and Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/events/show.html.erb
<p>Nom de l'event : <%= @event.title %></p>
<p>Description de l'event : <%= @event.description %></p>
<p>Le nombre d'inscrits est de <%= @event.title %></p>
<p>Date de fin de l'event :<%= @event.start_date + @event.duration %></p>
<p>Date de début de l'event :<%= @event.start_date %></p>
<p>Lieu de l'event : <%= @event.location %></p>
<p>Tarot de l'event : <%= @event.price %>€</p>

<%= button_to "Payer l'event", checkout_create_path(total: @event.price ), class: "btn btn-primary", data: { turbo: false } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
  <script src="https://js.stripe.com/v3/"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Eventbrite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Events</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/events/new">Créer un event</a>
      </li>
      <li class="nav-item dropdown">
      <% if user_signed_in? %>
        <a class="nav-link dropdown-toggle" href="/users/<%= current_user.id %>" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Mon profil
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/users/<%= current_user.id %>">Mon profil</a>
          <a class="dropdown-item" href="/users/sign_out">Se déconnecter</a>
        </div>
        <% else %>
        <a class="nav-link dropdown-toggle"  id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          S'inscrire/Se connecter
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/users/new">S'inscrire</a>
          <a class="dropdown-item" href="/users/sign_in">Se connecter</a>
        </div>
      <% end %>
      </li>
    </ul>
  </div>
</nav>
  
  <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/testings/_form.html.erb
<%= form_with(model: testing) do |form| %>
  <% if testing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(testing.errors.count, "error") %> prohibited this testing from being saved:</h2>

      <ul>
        <% testing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_area :bio %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/testings/_testing.html.erb
<div id="<%= dom_id testing %>">
  <p>
    <strong>Username:</strong>
    <%= testing.username %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= testing.bio %>
  </p>

</div>

app/views/testings/edit.html.erb
<h1>Editing testing</h1>

<%= render "form", testing: @testing %>

<br>

<div>
  <%= link_to "Show this testing", @testing %> |
  <%= link_to "Back to testings", testings_path %>
</div>

app/views/testings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Testings</h1>

<div id="testings">
  <% @testings.each do |testing| %>
    <%= render testing %>
    <p>
      <%= link_to "Show this testing", testing %>
    </p>
  <% end %>
</div>

<%= link_to "New testing", new_testing_path %>

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Dropdown button
  </button>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="#">Action</a></li>
    <li><a class="dropdown-item" href="#">Another action</a></li>
    <li><a class="dropdown-item" href="#">Something else here</a></li>
  </ul>
</div>

app/views/testings/new.html.erb
<h1>New testing</h1>

<%= render "form", testing: @testing %>

<br>

<div>
  <%= link_to "Back to testings", testings_path %>
</div>

app/views/testings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @testing %>

<div>
  <%= link_to "Edit this testing", edit_testing_path(@testing) %> |
  <%= link_to "Back to testings", testings_path %>

  <%= button_to "Destroy this testing", @testing, method: :delete %>
</div>

app/views/users/show.html.erb
<body>
     <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Voici tous les events rejoints amig@ !</h1>
          <p>Youhou ! </p>
          <p>Tip top ! </p>
          <p>Appréciez le design du site ! </p>
        </div>
     </div>

     <h2><%= current_user.first_name %></h2>
     <h2><%= current_user.last_name %></h2>
     <h2><%= current_user.description %></h2>
     <h2><%= current_user.email %></h2>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            <% @user_events.each do |user_events| %>
              <div class="col-md-4">
                <h2><%= user_events.title %></h2>
                <p><%= user_events.description %> </p>
                <p><a class="btn btn-secondary" href="/events/<%= user_events.id %>" role="button">Carte de l'event &raquo;</a></p>
                <%= button_to "Payer l'event", checkout_create_path(total: user_events.price ), class: "btn btn-primary", data: { turbo: false } %>
              </div>
            <% end%>
        </div>

        <hr>

      </div> <!-- /container -->

    </main>

    <footer class="container">
      <p>&copy; Copyright 2023</p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
</body>